name: firebase_api_example
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  functions_framework: any
  shelf: ^1.0.0

dev_dependencies:
  build_runner: ^1.10.2
  functions_framework_builder: any
  googleapis: ^2.0.0
  googleapis_auth: ^1.0.0

dependency_overrides:
  functions_framework:
    path: ../../functions_framework
  functions_framework_builder:
    path: ../../functions_framework_builder

  # Until build_runner is updated
  io: ^1.0.0
