name: firebase_api_example
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  functions_framework: any
  shelf: ^0.7.9

dev_dependencies:
  build_runner: ^1.10.2
  functions_framework_builder: any
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12

dependency_overrides:
  functions_framework:
    path: ../../functions_framework
  functions_framework_builder:
    path: ../../functions_framework_builder
